version: '3.8'

services:
  app:  
    image: node 
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app

  database:
    container_name: mongo-server
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example